services:

  postgres:
    build:
      context: ./Docker/postgres/
      dockerfile: Dockerfile
    env_file:
      - .env
    expose:
      - "5432"
    restart: always 

  admin_proj:
    build:
      context: ./Docker/admin_proj
      dockerfile: Dockerfile
    expose:
      - "8000"
    links:
      - postgres
    depends_on:
      - postgres
    restart: always
    env_file: .env
    volumes:
      - ./Docker/admin_proj/:/var/www/app/

  # trading_bot:
  #   build:
  #     context: ./Docker/trading_bot/
  #     dockerfile: Dockerfile
  #   env_file:
  #     - .env
  #   expose:
  #     - "8000"
  #   volumes:
  #     - ./Docker/trading_bot/:/var/www/trading_bot/
  #   links:
  #     - postgres
  #   depends_on:
  #     - postgres
  #     - admin_proj
  #   restart: always

  nginx:
    build:
      context: ./Docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./Docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./Docker/admin_proj/admin_proj/static/:/static/
      - ./Docker/admin_proj/admin_proj/media/:/media/
    ports:
      - "80:80"
    restart: always
    links:
      - postgres
      - admin_proj
      # - trading_bot
    depends_on:
      - postgres
      - admin_proj
      # - trading_bot