# Generated by Django 3.2.9 on 2021-11-24 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSystem',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False, verbose_name='Уникальный slug')),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('message', models.TextField(max_length=1000, verbose_name='Сообщение пользователю при оплате')),
            ],
            options={
                'verbose_name': 'Платежная система',
                'verbose_name_plural': 'Платежные системы',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('key', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Ключ поста')),
                ('message', models.TextField(max_length=5000, verbose_name='Сообщение')),
                ('is_draft', models.BooleanField(default=True, verbose_name='Черновик')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('month', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='Длительность подписки мес')),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('chat_id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Telegram Chat id')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Псевдоним')),
                ('extra', models.JSONField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Дополнительное описание')),
            ],
            options={
                'verbose_name': 'Пользователь tg',
                'verbose_name_plural': 'Пользователи tg',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Дата начала подписки')),
                ('is_active', models.BooleanField(default=False, verbose_name='Подписка активна')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='admin_proj.rate')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='admin_proj.tguser')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Подписка'), (2, 'Обучение')], verbose_name='Тип оплаты')),
                ('is_payed', models.BooleanField(default=False, verbose_name='Инвойс оплачен')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='Дата оплаты')),
                ('payment_system', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='admin_proj.paymentsystem')),
                ('rate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='admin_proj.rate')),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoice_list', to='admin_proj.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoice_list', to='admin_proj.tguser')),
            ],
            options={
                'verbose_name': 'Инвойс',
                'verbose_name_plural': 'Инвойсы',
                'ordering': ('-created_at',),
            },
        ),
    ]
